### ISSUE TITLE
Provide more docker options

### ISSUE THREAD

**Issue by jpambrun** [gportay/dosh#4]
As a nice to have, and I might tackle that in the future. 

It would be nice to : 
    1) have a env variable to specify an alternative docker executable (for instance nvidia-docker);
    2) have a switch to pass arbitrary arguments to docker (for instance -p to map ports).

Again, thanks for the super awesome utility.

**Comment by gportay** [comment]
Hi Jean-François,

>  1) have a env variable to specify an alternative docker executable (for instance nvidia-docker);

Okay.

I will add a `DOCKER` environment variable quite soon; so you will be able to run `DOCKER=nvidia-docker dosh`.

Do not hesitate to send PRs if you have modified already the code of dosh ;)

> 2) have a switch to pass arbitrary arguments to docker (for instance -p to map ports).

You already can pass extra arguments to `docker` using `DOSH_DOCKER_RUN_EXTRA_OPTS`. See https://github.com/gazoo74/dosh#docker-extra-options.

I pushed today support for `.doshrc` which is a per folder/project file that is sourced by dosh before running any docker command. It is not yet documented :(

As example, you can have a `.doshrc` that overrides docker options:

```
$ cat .doshrc
DOSH_DOCKER_RUN_EXTRA_OPTS+=" --publish 127.0.0.1:1234:1234"
```

```
$ dosh -c "nc -lkp 1234"
```

```
$ nc localhost 1234
```

Thanks you for you interest in dosh ;)

**Comment by gportay** [comment]
The idea beside the encapsulation of docker extra options in an environment variable is to *NOT* implement all option set in dosh.

**Comment by jpambrun** [comment]
That per-project .doshrc idea is absolutely awesome!

You close these issues way too fast. I had temporarily 'solved' my issues by hard-coding what I needed, but I was in the middle of something and I didn't what to shift focus so I opened the ticked to remember.  in addition, my script foo is obviously miles behind yours, it would have taken me quite some time to craft a respectable PR. I *really* appreciate it, but I hope you didn't drop something to address this..

Seriously, dosh is already such a time saver. I cannot commend you enough.
