### ISSUE TITLE
DOSH_DOCKER_RUN_EXTRA_OPTS doesn't work

### ISSUE THREAD

**Issue by jpambrun-vida** [gportay/dosh#6]
I have a simple doshrc
```
DOSH_DOCKER_RUN_EXTRA_OPTS="-p 1234:1234"
DOSHELL="/bin/bash"
```

But I get
```
> dosh
docker: invalid hostPort:  1234.
```

With dry run:
```
> dosh --dry-run
exec docker run --rm --volume /home/jpambrun/work/pyspark:/home/jpambrun/work/pyspark:rw --user 1000:1000 --interactive --tty --workdir /home/jpambrun/work/pyspark --env DOSHLVL=1 --entrypoint /bin/bash -p\ 1234:1234 dosh-jpambrun-689c3880773a6a0a8b0c56df249f5b66fefcc683e409444d52e69e71afd58e15
```

The extra `\` is suspicious. Running the command as-is reproduce the issue(invalid hostPort), removing the extra `\` works.

**Comment by jpambrun-vida** [comment]
It stopped working from 9653b69df963ea4698dfe3374b93a4d9fbfec5eb

**Comment by gportay** [comment]
My apologies, I have introduced a breaking change to allow setting parameters with spaces.

So, if you need to pass multiple arguments to docker (that is pretty much always the case) you should use bash arrays in your doshrc.

Try this:

```
DOSH_DOCKER_RUN_EXTRA_OPTS=(-p 1234:1234)
```

**Comment by gportay** [comment]
Tell me if this works for you or if you prefer I find a better solution to split the string into words.

**Comment by jpambrun-vida** [comment]
The proposed approach works. I just didn't quite get that from the doc.

**Comment by gportay** [comment]
@jpambrun-vida, in the end, I am doing the conversion to bash array after the `doshrc` is sourced to avoid a breaking change. but... the version 6 will remain broken.
